; Reassemblable source of ES1869.DRV, ESS's wave, mixer and aux driver for
; the ES1869 on Windows 95 (generated by tools/ne2asm.py from
; driver/ES1869.DRV 4.04.00.1319, with src/es1869/names.txt).
;
; Usage:
;   `python3 tools/build_es1869drv.py [--stock]`
;
; ESS's code keeps its addresses: a change is an instruction of the same
; length under %if ES1869_FIX, or new code after ESS's.
;
; (c) 2026 Ethan Halsall <ethan.s.halsall@gmail.com>
;
; Licensed under GPL Version 3.0

%ifndef ES1869_FIX
%define ES1869_FIX 1
%endif

        bits 16
%include "ne16.inc"

        section seg1 progbits start=0 vstart=0 align=1
%include "seg1.asm"

        section seg2 progbits follows=seg1 vstart=0 align=1
%include "seg2.asm"

        section seg3 progbits follows=seg2 vstart=0 align=1
%include "seg3.asm"

        section seg4 progbits follows=seg3 vstart=0 align=1
%include "seg4.asm"

        section seg5 progbits follows=seg4 vstart=0 align=1
%include "seg5.asm"

        section seg6 progbits follows=seg5 vstart=0 align=1
%include "seg6.asm"

        section seg7 progbits follows=seg6 vstart=0 align=1
%include "seg7.asm"

        section link progbits follows=seg7 vstart=0 align=1
%include "link.inc"
