; ICOD is object 7 of ES1869.VXD (code and data, flags 2015h).
; Generated by tools/vxd2asm.py, then maintained by hand.
; Trailing comments give the original object offset.

section ICOD progbits alloc exec nowrite align=1

; Sys_Dynamic_Device_Init
AUDDRV_Dynamic_Init:
        push byte +0x0                                  ; 0000
        push byte +0x4                                  ; 0002
        VxDCall _Allocate_Device_CB_Area                ; 0004
        add esp,byte +0x8                               ; 000A
        or_ eax,eax                                     ; 000D
        jnz short L7_0013                               ; 000F
L7_0011:
        stc                                             ; 0011
        ret                                             ; 0012
L7_0013:
        mov [AUDDRV_Globals],eax                        ; 0013
        mov eax,0x5                                     ; 0018
        mov ecx,0x4                                     ; 001D
        VxDCall List_Create                             ; 0022
        jc short L7_0011                                ; 0028
        mov [dword ADI_List],esi                        ; 002A
        VxDCall Get_Sys_VM_Handle                       ; 0030
        mov edi,[dword AUDDRV_Globals]                  ; 0036
        push ebx                                        ; 003C
L7_003D:
        mov eax,0x5                                     ; 003D
%if ESSREG_EXT
        mov ecx,ESSREG_NODE_SIZE                        ; essreg: room for NODE_VFM
%else
        mov ecx,0x2e                                    ; 0042
%endif
        VxDCall List_Create                             ; 0047
        jc short L7_0088                                ; 004D
        mov [edi+ebx],esi                               ; 004F
        VxDCall Get_Next_VM_Handle                      ; 0052
        cmp ebx,[esp]                                   ; 0058
        jnz short L7_003D                               ; 005B
        pop ebx                                         ; 005D
        mov eax,0x5                                     ; 005E
        mov ecx,0x6                                     ; 0063
        VxDCall List_Create                             ; 0068
        jc short L7_0011                                ; 006E
        mov [dword D1_02B1],esi                         ; 0070
        mov eax,0x15000e                                ; 0076
        mov esi,L1_04B8                                 ; 007B
        VxDCall Hook_Device_Service                     ; 0080
        clc                                             ; 0086
        ret                                             ; 0087
L7_0088:
        pop ebx                                         ; 0088
        jmp short L7_0011                               ; 0089
        db 0xcc                                         ; 008B
