; MCOD is object 2 of ES1869.VXD (code and data, flags A045h).
; Generated by tools/vxd2asm.py, then maintained by hand.
; Trailing comments give the original object offset.

section MCOD progbits alloc exec nowrite align=1

global D2_0000

D2_0000:
        db 0x04, 0x00, 0x00, 0x00                       ; 0000
        dd D2_0018                                      ; 0004
        db 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x4c, 0x00, 0x9b, 0x00, 0xea, 0x00, 0x05, 0x01, 0xcc, 0xcc ; 0008
D2_0018:
        db "Unable to play sound - the ESS AudioDrive is in use by another application.", 0 ; 0018
        db "Unable to play MIDI - the ESS FM Synthesizer is in use by another application.", 0 ; 0064
        db "Unable to access MIDI port - the ESS MPU-401 is in use by another application.", 0 ; 00B3
        db "ES1869 Direct Sound Driver", 0              ; 0102
