; PDAT is object 6 of ES1869.VXD (data, flags 2023h).
; Generated by tools/vxd2asm.py, then maintained by hand.
; Trailing comments give the original object offset.

section PDAT progbits alloc noexec write align=1

global D6_035C, D6_037C

; 9 x {value name, "Config"} read at init
Registry_Value_Table:
        db "Disable Warning", 0                         ; 0000
D6_0010:
        db "Config", 0                                  ; 0010
        db 0x00                                         ; 0017
D6_0018:
        db "Multiple FM Support", 0                     ; 0018
D6_002C:
        db "Config", 0                                  ; 002C
        db 0x00                                         ; 0033
D6_0034:
        db "Do Not Want ES689", 0                       ; 0034
        db 0x00, 0x00                                   ; 0046
D6_0048:
        db "Config", 0                                  ; 0048
        db 0x00                                         ; 004F
D6_0050:
        db "DOS MPU-401 Interrupts", 0                  ; 0050
        db 0x00                                         ; 0067
D6_0068:
        db "Config", 0                                  ; 0068
        db 0x00                                         ; 006F
D6_0070:
        db "Single Mode DMA", 0                         ; 0070
D6_0080:
        db "Config", 0                                  ; 0080
        db 0x00                                         ; 0087
D6_0088:
        db "HwVolume 2-Wire Mode", 0                    ; 0088
        db 0x00, 0x00, 0x00                             ; 009D
D6_00A0:
        db "Config", 0                                  ; 00A0
        db 0x00                                         ; 00A7
D6_00A8:
        db "HwVolume Count By 3", 0                     ; 00A8
D6_00BC:
        db "Config", 0                                  ; 00BC
        db 0x00                                         ; 00C3
D6_00C4:
        db "Disable Mic Gain", 0                        ; 00C4
        db 0x00, 0x00, 0x00                             ; 00D5
D6_00D8:
        db "Config", 0                                  ; 00D8
        db 0x00                                         ; 00DF
D6_00E0:
        db "Want Local Powerdown", 0                    ; 00E0
        db 0x00, 0x00, 0x00                             ; 00F5
D6_00F8:
        db "Config", 0                                  ; 00F8
        db 0x00                                         ; 00FF
D6_0100:
        db "AUDDRV: ", 0                                ; 0100
        db 0x00, 0x00, 0x00                             ; 0109
D6_010C:
        db 0x49, 0x52, 0x51, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x69 ; 010C
        db 0x6e, 0x67, 0x20, 0x28, 0x25, 0x78, 0x3a, 0x25, 0x78, 0x29, 0x0a, 0x00 ; 011C
D6_0128:
        db 0x44, 0x4d, 0x41, 0x20, 0x6e, 0x6f, 0x74, 0x20, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x69 ; 0128
        db 0x6e, 0x67, 0x20, 0x28, 0x25, 0x78, 0x3a, 0x25, 0x78, 0x29, 0x0a, 0x00 ; 0138
D6_0144:
        db "midi\esfm.drv", 0                           ; 0144
        db 0x00, 0x00                                   ; 0152
D6_0154:
        db "midi\essmpu.drv", 0                         ; 0154
D6_0164:
        db "A%03X I%d D%d", 0                           ; 0164
        db 0x00, 0x00                                   ; 0172
D6_0174:
        db "BLASTER", 0                                 ; 0174
D6_017C:
        db "BLASTER", 0                                 ; 017C
D6_0184:
        db "VIRTUAL\ESS1869-DMAEmulation", 0            ; 0184
        db 0x00, 0x00, 0x00                             ; 01A1
D6_01A4:
        db "A%03X I%d D%d", 0                           ; 01A4
        db 0x00, 0x00                                   ; 01B2
D6_01B4:
        db "BLASTER", 0                                 ; 01B4
D6_01BC:
        db "BLASTER", 0                                 ; 01BC
; 0000-000B: wave/DSP and device functions
API_Group0_Funcs:
        dd API_x000_GetVersion                          ; 01C4
        dd API_0001_GetInfo                             ; 01C8
        dd API_0002_Acquire                             ; 01CC
        dd API_0003_Release                             ; 01D0
        dd API_0004_GetDMACount                         ; 01D4
        dd API_0005_GPO                                 ; 01D8
        dd API_0006_SetHwVolCallback                    ; 01DC
        dd API_0007_SetupPIOBuffer                      ; 01E0
        dd API_0008_GetConfigPort                       ; 01E4
        dd API_0009_SetCallback2                        ; 01E8
        dd API_000A_GetGlobalFlag                       ; 01EC
        dd API_000B_SetCallback3                        ; 01F0
; 0100-0103: FM (ESFM.DRV)
API_Group1_Funcs:
        dd API_x000_GetVersion                          ; 01F4
        dd API_0101_FM_GetInfo                          ; 01F8
        dd API_0102_FM_Acquire                          ; 01FC
        dd API_0103_FM_Release                          ; 0200
; 0200-0201: notification clients
API_Group2_Funcs:
        dd API_0200_RegisterNotify                      ; 0204
        dd API_0201_UnregisterNotify                    ; 0208
; 0300-0303: MPU-401 (ESSMPU.DRV)
API_Group3_Funcs:
        dd API_x000_GetVersion                          ; 020C
        dd API_0301_MPU_GetInfo                         ; 0210
        dd API_0302_MPU_Acquire                         ; 0214
        dd API_0303_MPU_Release                         ; 0218
; 4 x {dword count, dword function table}
API_Group_Table:
        db 0x0c, 0x00, 0x00, 0x00                       ; 021C
        dd API_Group0_Funcs                             ; 0220
        db 0x04, 0x00, 0x00, 0x00                       ; 0224
        dd API_Group1_Funcs                             ; 0228
        db 0x02, 0x00, 0x00, 0x00                       ; 022C
        dd API_Group2_Funcs                             ; 0230
        db 0x04, 0x00, 0x00, 0x00                       ; 0234
        dd API_Group3_Funcs                             ; 0238
D6_023C:
        db 0x7c, 0x1a, 0x32, 0x36, 0x38, 0x3e, 0x3a, 0x3c, 0x64, 0x00 ; 023C
D6_0246:
        db 0x60, 0x62, 0x00                             ; 0246
D6_0249:
        db 0x66, 0xa1, 0xc2, 0xf1, 0xea, 0xe7, 0x71, 0xaa, 0xc7, 0x63, 0x33, 0x1b, 0x0d, 0x96, 0xdb, 0x6d ; 0249
        db 0xa4, 0x50, 0x28, 0x16, 0x9b, 0x4d, 0xb6, 0xc9, 0xf4, 0x78, 0x3e, 0x8d, 0xd6, 0xfb, 0x7f, 0x3d ; 0259
D6_0269:
        db "tvxz", 0                                    ; 0269
        db 0x00, 0x00                                   ; 026E
D6_0270:
        db 0x10, 0x00, 0x00, 0x00                       ; 0270
        dd DSP_Port_Trap                                ; 0274
        db 0x01, 0x00                                   ; 0278
        dd DSP_Port_Trap                                ; 027A
        db 0x02, 0x00                                   ; 027E
        dd DSP_Port_Trap                                ; 0280
        db 0x03, 0x00                                   ; 0284
        dd DSP_Port_Trap                                ; 0286
        db 0x04, 0x00                                   ; 028A
        dd DSP_Port_Trap                                ; 028C
        db 0x05, 0x00                                   ; 0290
        dd DSP_Port_Trap                                ; 0292
        db 0x06, 0x00                                   ; 0296
        dd DSP_Port_Trap                                ; 0298
        db 0x07, 0x00                                   ; 029C
        dd DSP_Port_Trap                                ; 029E
        db 0x08, 0x00                                   ; 02A2
        dd DSP_Port_Trap                                ; 02A4
        db 0x09, 0x00                                   ; 02A8
        dd DSP_Port_Trap                                ; 02AA
        db 0x0a, 0x00                                   ; 02AE
        dd DSP_Port_Trap                                ; 02B0
        db 0x0b, 0x00                                   ; 02B4
        dd DSP_Port_Trap                                ; 02B6
        db 0x0c, 0x00                                   ; 02BA
        dd DSP_Port_Trap                                ; 02BC
        db 0x0d, 0x00                                   ; 02C0
        dd DSP_Port_Trap                                ; 02C2
        db 0x0e, 0x00                                   ; 02C6
        dd DSP_Port_Trap                                ; 02C8
        db 0x0f, 0x00                                   ; 02CC
        dd DSP_Port_Trap                                ; 02CE
D6_02D2:
        db 0x10, 0x00, 0x00, 0x00                       ; 02D2
        dd FM_Port_Trap                                 ; 02D6
        db 0x01, 0x00                                   ; 02DA
        dd FM_Port_Trap                                 ; 02DC
        db 0x02, 0x00                                   ; 02E0
        dd FM_Port_Trap                                 ; 02E2
        db 0x03, 0x00                                   ; 02E6
        dd FM_Port_Trap                                 ; 02E8
        db 0x04, 0x00                                   ; 02EC
        dd DSP_Port_Trap                                ; 02EE
        db 0x05, 0x00                                   ; 02F2
        dd DSP_Port_Trap                                ; 02F4
        db 0x06, 0x00                                   ; 02F8
        dd DSP_Port_Trap                                ; 02FA
        db 0x07, 0x00                                   ; 02FE
        dd DSP_Port_Trap                                ; 0300
        db 0x08, 0x00                                   ; 0304
        dd FM_Port_Trap                                 ; 0306
        db 0x09, 0x00                                   ; 030A
        dd FM_Port_Trap                                 ; 030C
        db 0x0a, 0x00                                   ; 0310
        dd DSP_Port_Trap                                ; 0312
        db 0x0b, 0x00                                   ; 0316
        dd DSP_Port_Trap                                ; 0318
        db 0x0c, 0x00                                   ; 031C
        dd DSP_Port_Trap                                ; 031E
        db 0x0d, 0x00                                   ; 0322
        dd DSP_Port_Trap                                ; 0324
        db 0x0e, 0x00                                   ; 0328
        dd DSP_Port_Trap                                ; 032A
        db 0x0f, 0x00                                   ; 032E
        dd DSP_Port_Trap                                ; 0330
D6_0334:
        db 0x04, 0x00, 0x00, 0x00                       ; 0334
        dd FM_Port_Trap                                 ; 0338
        db 0x01, 0x00                                   ; 033C
        dd FM_Port_Trap                                 ; 033E
        db 0x02, 0x00                                   ; 0342
        dd FM_Port_Trap                                 ; 0344
        db 0x03, 0x00                                   ; 0348
        dd FM_Port_Trap                                 ; 034A
D6_034E:
        db 0x02, 0x00, 0x00, 0x00                       ; 034E
        dd MPU_Port_Trap                                ; 0352
        db 0x01, 0x00                                   ; 0356
        dd MPU_Port_Trap                                ; 0358
D6_035C:
        db 0x00, 0x00, 0x04, 0x00                       ; 035C
        dd D1_054C                                      ; 0360
        db 0x00, 0x00, 0x00, 0x00                       ; 0364
        dd L1_0734                                      ; 0368
        dd L1_07C4                                      ; 036C
        db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ; 0370
D6_037C:
        db 0x00, 0x00, 0x04, 0x00                       ; 037C
        dd L1_07F0                                      ; 0380
        db 0x00, 0x00, 0x00, 0x00                       ; 0384
        dd L1_082C                                      ; 0388
        dd L1_083C                                      ; 038C
        db 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 ; 0390
D6_039C:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 039C
        db 0x74, 0x65, 0x20, 0x44, 0x53, 0x50, 0x0a, 0x00 ; 03AC
D6_03B4:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 03B4
        db 0x74, 0x65, 0x20, 0x4d, 0x50, 0x55, 0x0a, 0x00 ; 03C4
D6_03CC:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 03CC
        db 0x74, 0x65, 0x20, 0x46, 0x4d, 0x0a, 0x00     ; 03DC
D6_03E3:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 03E3
        db 0x74, 0x65, 0x20, 0x49, 0x52, 0x51, 0x0a, 0x00 ; 03F3
D6_03FB:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 03FB
        db 0x74, 0x65, 0x20, 0x4d, 0x50, 0x55, 0x49, 0x52, 0x51, 0x0a, 0x00 ; 040B
D6_0416:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 0416
        db 0x74, 0x65, 0x20, 0x44, 0x4d, 0x41, 0x0a, 0x00 ; 0426
D6_042E:
        db 0x75, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x20, 0x74, 0x6f, 0x20, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61 ; 042E
        db 0x74, 0x65, 0x20, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x0a, 0x00 ; 043E
D6_0449:
        db "_DEV0000", 0                                ; 0449
D6_0452:
        db "ESS0006", 0                                 ; 0452
D6_045A:
        db "CPQB023", 0                                 ; 045A
D6_0462:
        db "CPQB0AB", 0                                 ; 0462
D6_046A:
        db "CPQB0AC", 0                                 ; 046A
D6_0472:
        db "CPQB0AD", 0                                 ; 0472
        db 0x00, 0x00, 0x87, 0x83, 0x81, 0x82, 0x00, 0x8b, 0x89, 0x8a, 0x00, 0x00, 0x00, 0x00 ; 047A
D6_0488:
        dd L5_2A30                                      ; 0488
        dd L5_2A80                                      ; 048C
        dd L5_2A90                                      ; 0490
        dd L5_2AA0                                      ; 0494
        dd L5_2B20                                      ; 0498
        dd L5_2CD0                                      ; 049C
        dd L5_2B50                                      ; 04A0
        dd L5_2BA0                                      ; 04A4
        dd L5_2CB0                                      ; 04A8
D6_04AC:
        db "ES1869.VXD", 0                              ; 04AC
        db 0x00                                         ; 04B7
D6_04B8:
        db "dsound.vxd", 0                              ; 04B8
        db 0x00, 0x00, 0x00, 0x00, 0x00                 ; 04C3
D6_04C8:
        dd L5_2E90                                      ; 04C8
        dd L5_2EE0                                      ; 04CC
        dd L5_2E60                                      ; 04D0
        dd L5_2EF0                                      ; 04D4
        dd L5_2F00                                      ; 04D8
        dd L5_2F10                                      ; 04DC
        dd L5_2F90                                      ; 04E0
        dd L5_2FC0                                      ; 04E4
        dd L5_2FE0                                      ; 04E8
        dd L5_2FF0                                      ; 04EC
        dd L5_30D0                                      ; 04F0
        dd L5_3220                                      ; 04F4
