; PNP is object 4 of ES1869.VXD (code and data, flags 2005h).
; Generated by tools/vxd2asm.py, then maintained by hand.
; Trailing comments give the original object offset.

section PNP progbits alloc exec nowrite align=1

L4_0000:
        push ebp                                        ; 0000
        mov_ ebp,esp                                    ; 0001
        push edi                                        ; 0003
        push byte +0x0                                  ; 0004
        push dword [ebp+0x8]                            ; 0006
        call _AUDDRV_Get_pADI_From_XXX                  ; 0009
        add esp,byte +0x8                               ; 000E
        or_ edi,edi                                     ; 0011
        jz short L4_0027                                ; 0013
        cmp dword [edi+0x35],byte +0x0                  ; 0015
        jnz short L4_002E                               ; 0019
        cmp dword [edi+0x3d],byte +0x0                  ; 001B
        jnz short L4_002E                               ; 001F
        cmp dword [edi+0x45],byte +0x0                  ; 0021
        jnz short L4_002E                               ; 0025
L4_0027:
        mov eax,0x0                                     ; 0027
        jmp short L4_0033                               ; 002C
L4_002E:
        mov eax,0xffffffff                              ; 002E
L4_0033:
        pop edi                                         ; 0033
        pop ebp                                         ; 0034
        ret                                             ; 0035
L4_0036:
        cmp eax,byte +0x40                              ; 0036
        jng short L4_0040                               ; 0039
        mov eax,0x40                                    ; 003B
L4_0040:
        add eax,byte +0x3                               ; 0040
        shr eax,byte 0x2                                ; 0043
L4_0046:
        mov_ ebx,eax                                    ; 0046
        dec eax                                         ; 0048
        bsr cx,ax                                       ; 0049
        inc cl                                          ; 004D
        mov eax,0x1                                     ; 004F
        shl eax,cl                                      ; 0054
        dec eax                                         ; 0056
        mov_ ecx,ebx                                    ; 0057
        push ecx                                        ; 0059
        sub esp,byte +0x4                               ; 005A
        mov_ ebx,esp                                    ; 005D
        push byte +0xe                                  ; 005F
        push ebx                                        ; 0061
        push dword 0xfff                                ; 0062
        push byte +0x0                                  ; 0067
        push eax                                        ; 0069
        push byte +0x0                                  ; 006A
        push byte +0x1                                  ; 006C
        push ecx                                        ; 006E
        VxDCall _PageAllocate                           ; 006F
        add esp,byte +0x20                              ; 0075
        pop ebx                                         ; 0078
        pop ecx                                         ; 0079
        or_ eax,eax                                     ; 007A
        jnz short L4_0088                               ; 007C
        mov_ eax,ecx                                    ; 007E
        shr eax,1                                       ; 0080
        jnz short L4_0046                               ; 0082
        xor_ ecx,ecx                                    ; 0084
        stc                                             ; 0086
        ret                                             ; 0087
L4_0088:
        shl ecx,byte 0xc                                ; 0088
        clc                                             ; 008B
        ret                                             ; 008C
L4_008D:
        push eax                                        ; 008D
        push ecx                                        ; 008E
        push esi                                        ; 008F
        push edi                                        ; 0090
        mov edi,[dword AUDDRV_Globals]                  ; 0091
        mov esi,[edi+ebx]                               ; 0097
        or_ esi,esi                                     ; 009A
        jz short L4_00C8                                ; 009C
        VxDCall List_Allocate                           ; 009E
        jc short L4_00C8                                ; 00A4
        push eax                                        ; 00A6
        mov_ edi,eax                                    ; 00A7
        xor_ eax,eax                                    ; 00A9
%if ESSREG_EXT
        mov ecx,ESSREG_NODE_SIZE                        ; essreg: clear NODE_VFM too
%else
        mov ecx,0x2e                                    ; 00AB
%endif
        shr ecx,byte 0x2                                ; 00B0
        rep stosd                                       ; 00B3
        pop eax                                         ; 00B5
        mov edi,[esp]                                   ; 00B6
        mov [eax+0x4],edi                               ; 00B9
        VxDCall List_Attach_Tail                        ; 00BC
        clc                                             ; 00C2
L4_00C3:
        pop edi                                         ; 00C3
        pop esi                                         ; 00C4
        pop ecx                                         ; 00C5
        pop eax                                         ; 00C6
        ret                                             ; 00C7
L4_00C8:
        stc                                             ; 00C8
        jmp short L4_00C3                               ; 00C9
L4_00CB:
        push eax                                        ; 00CB
        push ecx                                        ; 00CC
        push esi                                        ; 00CD
        push edi                                        ; 00CE
        pushf                                           ; 00CF
        mov esi,[dword AUDDRV_Globals]                  ; 00D0
        mov esi,[esi+ebx]                               ; 00D6
        or_ esi,esi                                     ; 00D9
        jz short L4_0103                                ; 00DB
        cli                                             ; 00DD
        VxDCall List_Get_First                          ; 00DE
        jz short L4_0103                                ; 00E4
L4_00E6:
        cmp [eax+0x4],edi                               ; 00E6
        jz short L4_00F5                                ; 00E9
        VxDCall List_Get_Next                           ; 00EB
        jz short L4_0103                                ; 00F1
        jmp short L4_00E6                               ; 00F3
L4_00F5:
        push eax                                        ; 00F5
        VxDCall List_Remove                             ; 00F6
        pop eax                                         ; 00FC
        VxDCall List_Deallocate                         ; 00FD
L4_0103:
        popf                                            ; 0103
        pop edi                                         ; 0104
        pop esi                                         ; 0105
        pop ecx                                         ; 0106
        pop eax                                         ; 0107
        ret                                             ; 0108
L4_0109:
        jmp short L4_0115                               ; 0109
L4_010B:
        mov esi,0x0                                     ; 010B
        jmp near L4_01CD                                ; 0110
L4_0115:
        push ebp                                        ; 0115
        mov_ ebp,esp                                    ; 0116
        sub esp,byte +0xc                               ; 0118
        pusha                                           ; 011B
        mov [ebp-0xc],edx                               ; 011C
        movzx ecx,word [edi]                            ; 011F
        mov_ eax,ecx                                    ; 0122
        shl eax,byte 0x2                                ; 0124
        add_ eax,ecx                                    ; 0127
        shl eax,1                                       ; 0129
        mov [ebp-0x4],eax                               ; 012B
        push dword 0x101                                ; 012E
        push eax                                        ; 0133
        VxDCall _HeapAllocate                           ; 0134
        add esp,byte +0x8                               ; 013A
        or_ eax,eax                                     ; 013D
        jz near L4_01C7                                 ; 013F
        mov [ebp-0x8],eax                               ; 0145
        push edi                                        ; 0148
        movzx ecx,word [edi]                            ; 0149
        push ecx                                        ; 014C
        mov edi,[ebp-0x8]                               ; 014D
L4_0150:
        push ecx                                        ; 0150
        mov ecx,0xa                                     ; 0151
        mov esi,L4_010B                                 ; 0156
        cld                                             ; 015B
        rep movsb                                       ; 015C
        pop ecx                                         ; 015E
        loop L4_0150                                    ; 015F
        pop ecx                                         ; 0161
        mov edi,[esp]                                   ; 0162
        mov esi,[ebp-0x8]                               ; 0165
        add edi,byte +0x2                               ; 0168
L4_016B:
        mov eax,[ebp-0xc]                               ; 016B
        mov [esi+0x1],eax                               ; 016E
        mov eax,[edi+0x2]                               ; 0171
        sub_ eax,esi                                    ; 0174
        sub eax,strict dword 0xa                        ; 0176
        mov [esi+0x6],eax                               ; 017B
        movzx edx,word [edi]                            ; 017E
        VxDCall Install_IO_Handler                      ; 0181
        jc short L4_019E                                ; 0187
        add edi,byte +0x6                               ; 0189
        add esi,strict dword 0xa                        ; 018C
        loop L4_016B                                    ; 0192
        pop edi                                         ; 0194
        mov eax,[ebp-0x8]                               ; 0195
        mov [esp+0x1c],eax                              ; 0198
        jmp short L4_01CD                               ; 019C
L4_019E:
        pop edi                                         ; 019E
        movzx eax,word [edi]                            ; 019F
        sub_ ecx,eax                                    ; 01A2
        neg ecx                                         ; 01A4
        jecxz L4_01B9                                   ; 01A6
        add edi,byte +0x2                               ; 01A8
L4_01AB:
        movzx edx,word [edi]                            ; 01AB
        VxDCall VMM_Service_0116                        ; 01AE
        add edi,byte +0x6                               ; 01B4
        loop L4_01AB                                    ; 01B7
L4_01B9:
        push byte +0x0                                  ; 01B9
        push dword [ebp-0x8]                            ; 01BB
        VxDCall _HeapFree                               ; 01BE
        add esp,byte +0x8                               ; 01C4
L4_01C7:
        xor_ eax,eax                                    ; 01C7
        mov [esp+0x1c],eax                              ; 01C9
L4_01CD:
        popa                                            ; 01CD
        add esp,byte +0xc                               ; 01CE
        pop ebp                                         ; 01D1
        ret                                             ; 01D2
L4_01D3:
        push ecx                                        ; 01D3
        push edx                                        ; 01D4
        push edi                                        ; 01D5
        push eax                                        ; 01D6
        movzx ecx,word [edi]                            ; 01D7
        add edi,byte +0x2                               ; 01DA
L4_01DD:
        movzx edx,word [edi]                            ; 01DD
        VxDCall VMM_Service_0116                        ; 01E0
        add edi,byte +0x6                               ; 01E6
        loop L4_01DD                                    ; 01E9
        pop eax                                         ; 01EB
        push byte +0x0                                  ; 01EC
        push eax                                        ; 01EE
        VxDCall _HeapFree                               ; 01EF
        add esp,byte +0x8                               ; 01F5
        pop edi                                         ; 01F8
        pop edx                                         ; 01F9
        pop ecx                                         ; 01FA
        ret                                             ; 01FB
; allocate and fill a device instance (ADI)
ADI_Create:
        push ebp                                        ; 01FC
        mov_ ebp,esp                                    ; 01FD
        sub esp,byte +0x4                               ; 01FF
        pusha                                           ; 0202
        mov dword [ebp-0x4],0x0                         ; 0203
        mov esi,[dword ADI_List]                        ; 020A
        or_ esi,esi                                     ; 0210
        jz near L4_05D5                                 ; 0212
        VxDCall List_Allocate                           ; 0218
        jc near L4_05D5                                 ; 021E
        mov [ebp-0x4],eax                               ; 0224
        VxDCall List_Attach_Tail                        ; 0227
        mov dword [eax],0x0                             ; 022D
        push byte +0x1                                  ; 0233
%if ESSREG_EXT
        push dword ESSREG_ADI_SIZE                      ; essreg: the extension's fields
%else
        push dword 0xe9                                 ; 0235
%endif
        VxDCall _HeapAllocate                           ; 023A
        add esp,byte +0x8                               ; 0240
        or_ eax,eax                                     ; 0243
        jz near L4_05D5                                 ; 0245
        mov_ edi,eax                                    ; 024B
        mov eax,[ebp-0x4]                               ; 024D
        mov [eax],edi                                   ; 0250
        mov eax,[ebp+0x8]                               ; 0252
        mov [edi+0x55],eax                              ; 0255
        mov word [edi+0xc9],0x0                         ; 0258
        mov eax,[ebp+0x2c]                              ; 0261
        mov [edi+0x4],ax                                ; 0264
        shr eax,byte 0x10                               ; 0268
        mov [edi+0x13],ax                               ; 026B
        mov ax,[ebp+0xc]                                ; 026F
        mov [edi+0x6],ax                                ; 0273
        mov ax,[ebp+0x10]                               ; 0277
        mov [edi+0x15],ax                               ; 027B
        mov byte [edi+0x11],0x17                        ; 027F
        mov ax,[ebp+0x1c]                               ; 0283
        mov [edi+0x12],al                               ; 0287
        mov ax,[ebp+0x14]                               ; 028A
        mov [edi+0x8],ax                                ; 028E
        mov ax,[ebp+0x18]                               ; 0292
        mov [edi+0xa],ax                                ; 0296
        mov ax,[ebp+0x30]                               ; 029A
        mov [edi+0xc],ax                                ; 029E
        mov ax,[ebp+0x34]                               ; 02A2
        mov [edi+0xe],al                                ; 02A6
        mov ax,[ebp+0x20]                               ; 02A9
        mov [edi+0xf],al                                ; 02AD
        mov ax,[ebp+0x24]                               ; 02B0
        mov [edi+0x10],al                               ; 02B4
        mov ax,[ebp+0x38]                               ; 02B7
        mov [edi+0x79],al                               ; 02BB
        call Get_AUDDRV_Version                         ; 02BE
        mov [edi+0x17],ax                               ; 02C3
        call L5_1C95                                    ; 02C7
        jc near L4_05D5                                 ; 02CC
        push edi                                        ; 02D2
        movzx ecx,byte [edi+0xf]                        ; 02D3
        mov [dword D6_035C],cx                          ; 02D7
        mov [dword D6_035C+0x1c wrt ..sym],edi          ; 02DE
        mov edi,D6_035C                                 ; 02E4
        VxDCall VPICD_Virtualize_IRQ                    ; 02E9
        pop edi                                         ; 02EF
        jnc short L4_0304                               ; 02F0
        push dword D6_03E3                              ; 02F2
        call L5_0300                                    ; 02F7
        add esp,byte +0x4                               ; 02FC
        jmp near L4_05D5                                ; 02FF
L4_0304:
        mov [edi+0x31],eax                              ; 0304
        VxDCall Get_Sys_VM_Handle                       ; 0307
        VxDCall VPICD_Get_Complete_Status               ; 030D
        test ecx,0x4                                    ; 0313
        jnz short L4_0321                               ; 0319
        or word [edi+0x4],0x8000                        ; 031B
L4_0321:
        movsx edx,word [ebp+0x30]                       ; 0321
        cmp edx,byte -0x1                               ; 0325
        jz short L4_0381                                ; 0328
        test word [edi+0x4],0x2000                      ; 032A
        jnz short L4_0381                               ; 0330
        push edi                                        ; 0332
        movzx ecx,byte [edi+0xe]                        ; 0333
        mov [dword D6_037C],cx                          ; 0337
        mov [dword D6_037C+0x1c wrt ..sym],edi          ; 033E
        mov edi,D6_037C                                 ; 0344
        VxDCall VPICD_Virtualize_IRQ                    ; 0349
        pop edi                                         ; 034F
        jnc short L4_0364                               ; 0350
        push dword D6_03FB                              ; 0352
        call L5_0300                                    ; 0357
        add esp,byte +0x4                               ; 035C
        jmp near L4_05D5                                ; 035F
L4_0364:
        mov [edi+0x2d],eax                              ; 0364
        VxDCall Get_Sys_VM_Handle                       ; 0367
        VxDCall VPICD_Get_Complete_Status               ; 036D
        test ecx,0x4                                    ; 0373
        jnz short L4_0381                               ; 0379
        or word [edi+0x4],0x4000                        ; 037B
L4_0381:
        mov esi,D6_02D2                                 ; 0381
        cmp word [ebp+0x14],byte -0x1                   ; 0386
        jnz short L4_0392                               ; 038B
        mov esi,D6_0270                                 ; 038D
L4_0392:
        movzx ecx,word [esi]                            ; 0392
        movzx edx,word [ebp+0xc]                        ; 0395
        push edi                                        ; 0399
        mov_ edi,esi                                    ; 039A
        add esi,byte +0x2                               ; 039C
L4_039F:
        mov [esi],dx                                    ; 039F
        inc edx                                         ; 03A2
        add esi,byte +0x6                               ; 03A3
        loop L4_039F                                    ; 03A6
        mov edx,[esp]                                   ; 03A8
        call L4_0109                                    ; 03AB
        pop edi                                         ; 03B0
        mov [edi+0x59],eax                              ; 03B1
        or_ eax,eax                                     ; 03B4
        jnz short L4_03CA                               ; 03B6
        push dword D6_039C                              ; 03B8
        call L5_0300                                    ; 03BD
        add esp,byte +0x4                               ; 03C2
        jmp near L4_05D5                                ; 03C5
L4_03CA:
        movsx edx,word [ebp+0x30]                       ; 03CA
        cmp edx,byte -0x1                               ; 03CE
        jz short L4_0410                                ; 03D1
        mov [edi+0xc],dx                                ; 03D3
        mov esi,D6_034E                                 ; 03D7
        movzx ecx,word [esi]                            ; 03DC
        push edi                                        ; 03DF
        mov_ edi,esi                                    ; 03E0
        add esi,byte +0x2                               ; 03E2
L4_03E5:
        mov [esi],dx                                    ; 03E5
        inc edx                                         ; 03E8
        add esi,byte +0x6                               ; 03E9
        loop L4_03E5                                    ; 03EC
        mov edx,[esp]                                   ; 03EE
        call L4_0109                                    ; 03F1
        pop edi                                         ; 03F6
        mov [edi+0x61],eax                              ; 03F7
        or_ eax,eax                                     ; 03FA
        jnz short L4_0410                               ; 03FC
        push dword D6_03B4                              ; 03FE
        call L5_0300                                    ; 0403
        add esp,byte +0x4                               ; 0408
        jmp near L4_05D5                                ; 040B
L4_0410:
        movsx edx,word [ebp+0x18]                       ; 0410
        cmp edx,byte -0x1                               ; 0414
        jz short L4_0452                                ; 0417
        mov esi,D6_0334                                 ; 0419
        movzx ecx,word [esi]                            ; 041E
        push edi                                        ; 0421
        mov_ edi,esi                                    ; 0422
        add esi,byte +0x2                               ; 0424
L4_0427:
        mov [esi],dx                                    ; 0427
        inc edx                                         ; 042A
        add esi,byte +0x6                               ; 042B
        loop L4_0427                                    ; 042E
        mov edx,[esp]                                   ; 0430
        call L4_0109                                    ; 0433
        pop edi                                         ; 0438
        mov [edi+0x5d],eax                              ; 0439
        or_ eax,eax                                     ; 043C
        jnz short L4_0452                               ; 043E
        push dword D6_03CC                              ; 0440
        call L5_0300                                    ; 0445
        add esp,byte +0x4                               ; 044A
        jmp near L4_05D5                                ; 044D
L4_0452:
        cmp word [ebp+0x38],byte +0x3                   ; 0452
        jna short L4_04B7                               ; 0457
        mov eax,[ebp+0x28]                              ; 0459
        shl eax,1                                       ; 045C
        call L4_0036                                    ; 045E
        mov [edi+0xcb],eax                              ; 0463
        mov [edi+0xcf],ebx                              ; 0469
        mov [edi+0xd7],ecx                              ; 046F
        mov [edi+0xd3],edx                              ; 0475
        jnc short L4_048F                               ; 047B
        push dword D6_042E                              ; 047D
        call L5_0300                                    ; 0482
        add esp,byte +0x4                               ; 0487
        jmp near L4_05D5                                ; 048A
L4_048F:
        push byte +0x0                                  ; 048F
        push byte +0x0                                  ; 0491
        push dword 0x92                                 ; 0493
        push ecx                                        ; 0498
        push edx                                        ; 0499
        VxDCall _BuildDescriptorDWORDs                  ; 049A
        add esp,byte +0x14                              ; 04A0
        push byte +0x0                                  ; 04A3
        push eax                                        ; 04A5
        push edx                                        ; 04A6
        VxDCall _Allocate_GDT_Selector                  ; 04A7
        add esp,byte +0xc                               ; 04AD
        mov [edi+0xdb],ax                               ; 04B0
L4_04B7:
        mov eax,[ebp+0x28]                              ; 04B7
        call L4_0036                                    ; 04BA
        mov [edi+0x19],eax                              ; 04BF
        mov [edi+0x1d],ebx                              ; 04C2
        mov [edi+0x25],ecx                              ; 04C5
        mov [edi+0x21],edx                              ; 04C8
        jnc short L4_04DF                               ; 04CB
        push dword D6_042E                              ; 04CD
        call L5_0300                                    ; 04D2
        add esp,byte +0x4                               ; 04D7
        jmp near L4_05D5                                ; 04DA
L4_04DF:
        push byte +0x0                                  ; 04DF
        push byte +0x0                                  ; 04E1
        push dword 0x92                                 ; 04E3
        push ecx                                        ; 04E8
        push edx                                        ; 04E9
        VxDCall _BuildDescriptorDWORDs                  ; 04EA
        add esp,byte +0x14                              ; 04F0
        push byte +0x0                                  ; 04F3
        push eax                                        ; 04F5
        push edx                                        ; 04F6
        VxDCall _Allocate_GDT_Selector                  ; 04F7
        add esp,byte +0xc                               ; 04FD
        mov [edi+0x29],ax                               ; 0500
        mov eax,[ebp+0x28]                              ; 0504
        call L4_0036                                    ; 0507
        mov [edi+0x7e],eax                              ; 050C
        mov [edi+0x82],ebx                              ; 050F
        mov [edi+0x8a],ecx                              ; 0515
        mov [edi+0x86],edx                              ; 051B
        jnc short L4_0535                               ; 0521
        push dword D6_042E                              ; 0523
        call L5_0300                                    ; 0528
        add esp,byte +0x4                               ; 052D
        jmp near L4_05D5                                ; 0530
L4_0535:
        push byte +0x0                                  ; 0535
        push byte +0x0                                  ; 0537
        push dword 0x92                                 ; 0539
        push ecx                                        ; 053E
        push edx                                        ; 053F
        VxDCall _BuildDescriptorDWORDs                  ; 0540
        add esp,byte +0x14                              ; 0546
        push byte +0x0                                  ; 0549
        push eax                                        ; 054B
        push edx                                        ; 054C
        VxDCall _Allocate_GDT_Selector                  ; 054D
        add esp,byte +0xc                               ; 0553
        mov [edi+0x8e],ax                               ; 0556
        movzx eax,word [ebp+0x38]                       ; 055D
        mov esi,L1_0870                                 ; 0561
        VxDCall VDMAD_Virtualize_Channel                ; 0566
        mov [edi+0x7a],eax                              ; 056C
        jnc short L4_0580                               ; 056F
        push dword D6_0416                              ; 0571
        call L5_0300                                    ; 0576
        add esp,byte +0x4                               ; 057B
        jmp short L4_05D5                               ; 057E
L4_0580:
        test dword [ebp+0x2c],0x20                      ; 0580
        jnz short L4_05AC                               ; 0587
        movzx eax,word [ebp+0x24]                       ; 0589
        mov esi,L1_0518                                 ; 058D
        VxDCall VDMAD_Virtualize_Channel                ; 0592
        mov [edi+0x4d],eax                              ; 0598
        jnc short L4_05AC                               ; 059B
        push dword D6_0416                              ; 059D
        call L5_0300                                    ; 05A2
        add esp,byte +0x4                               ; 05A7
        jmp short L4_05D5                               ; 05AA
L4_05AC:
        VxDCall Get_Sys_VM_Handle                       ; 05AC
        push ebx                                        ; 05B2
L4_05B3:
        call L4_008D                                    ; 05B3
        jc short L4_05D4                                ; 05B8
        VxDCall Get_Next_VM_Handle                      ; 05BA
        cmp ebx,[esp]                                   ; 05C0
        jnz short L4_05B3                               ; 05C3
        pop ebx                                         ; 05C5
        mov dword [esp+0x1c],0xffffffff                 ; 05C6
L4_05CE:
        popa                                            ; 05CE
        add esp,byte +0x4                               ; 05CF
        pop ebp                                         ; 05D2
        ret                                             ; 05D3
L4_05D4:
        pop ebx                                         ; 05D4
L4_05D5:
        mov edi,[ebp-0x4]                               ; 05D5
        or_ edi,edi                                     ; 05D8
        jz short L4_05E1                                ; 05DA
        call L4_05EB                                    ; 05DC
L4_05E1:
        mov dword [esp+0x1c],0x0                        ; 05E1
        jmp short L4_05CE                               ; 05E9
L4_05EB:
        push ebp                                        ; 05EB
        mov_ ebp,esp                                    ; 05EC
        sub esp,byte +0x4                               ; 05EE
        pusha                                           ; 05F1
        mov [ebp-0x4],edi                               ; 05F2
        mov edi,[edi]                                   ; 05F5
        or_ edi,edi                                     ; 05F7
        jz near L4_075A                                 ; 05F9
        xor_ esi,esi                                    ; 05FF
        xchg esi,[edi+0x51]                             ; 0601
        or_ esi,esi                                     ; 0604
        jz short L4_060E                                ; 0606
        VxDCall List_Destroy                            ; 0608
L4_060E:
        mov eax,[edi+0x4d]                              ; 060E
        or_ eax,eax                                     ; 0611
        jz short L4_061B                                ; 0613
        VxDCall VDMAD_Unvirtualize_Channel              ; 0615
L4_061B:
        mov eax,[edi+0x7a]                              ; 061B
        or_ eax,eax                                     ; 061E
        jz short L4_0628                                ; 0620
        VxDCall VDMAD_Unvirtualize_Channel              ; 0622
L4_0628:
        movzx eax,word [edi+0x8e]                       ; 0628
        or_ eax,eax                                     ; 062F
        jz short L4_064E                                ; 0631
        push byte +0x0                                  ; 0633
        push eax                                        ; 0635
        VxDCall _Free_GDT_Selector                      ; 0636
        add esp,byte +0x8                               ; 063C
        mov eax,[edi+0x7e]                              ; 063F
        push byte +0x0                                  ; 0642
        push eax                                        ; 0644
        VxDCall _PageFree                               ; 0645
        add esp,byte +0x8                               ; 064B
L4_064E:
        movzx eax,word [edi+0x29]                       ; 064E
        or_ eax,eax                                     ; 0652
        jz short L4_0671                                ; 0654
        push byte +0x0                                  ; 0656
        push eax                                        ; 0658
        VxDCall _Free_GDT_Selector                      ; 0659
        add esp,byte +0x8                               ; 065F
        mov eax,[edi+0x19]                              ; 0662
        push byte +0x0                                  ; 0665
        push eax                                        ; 0667
        VxDCall _PageFree                               ; 0668
        add esp,byte +0x8                               ; 066E
L4_0671:
        movzx eax,word [edi+0xdb]                       ; 0671
        or_ eax,eax                                     ; 0678
        jz short L4_069A                                ; 067A
        push byte +0x0                                  ; 067C
        push eax                                        ; 067E
        VxDCall _Free_GDT_Selector                      ; 067F
        add esp,byte +0x8                               ; 0685
        mov eax,[edi+0xcb]                              ; 0688
        push byte +0x0                                  ; 068E
        push eax                                        ; 0690
        VxDCall _PageFree                               ; 0691
        add esp,byte +0x8                               ; 0697
L4_069A:
        mov eax,[edi+0x5d]                              ; 069A
        or_ eax,eax                                     ; 069D
        jz short L4_06CC                                ; 069F
        mov esi,D6_0334                                 ; 06A1
        movzx ecx,word [esi]                            ; 06A6
        movsx edx,word [edi+0xa]                        ; 06A9
        or_ edx,edx                                     ; 06AD
        js short L4_06CC                                ; 06AF
        push edi                                        ; 06B1
        mov_ edi,esi                                    ; 06B2
        add esi,byte +0x2                               ; 06B4
L4_06B7:
        mov [esi],dx                                    ; 06B7
        inc edx                                         ; 06BA
        add esi,byte +0x6                               ; 06BB
        loop L4_06B7                                    ; 06BE
        mov eax,[esp]                                   ; 06C0
        mov eax,[eax+0x5d]                              ; 06C3
        call L4_01D3                                    ; 06C6
        pop edi                                         ; 06CB
L4_06CC:
        mov eax,[edi+0x61]                              ; 06CC
        or_ eax,eax                                     ; 06CF
        jz short L4_06FA                                ; 06D1
        mov esi,D6_034E                                 ; 06D3
        movzx ecx,word [esi]                            ; 06D8
        movzx edx,word [edi+0xc]                        ; 06DB
        push edi                                        ; 06DF
        mov_ edi,esi                                    ; 06E0
        add esi,byte +0x2                               ; 06E2
L4_06E5:
        mov [esi],dx                                    ; 06E5
        inc edx                                         ; 06E8
        add esi,byte +0x6                               ; 06E9
        loop L4_06E5                                    ; 06EC
        mov eax,[esp]                                   ; 06EE
        mov eax,[eax+0x61]                              ; 06F1
        call L4_01D3                                    ; 06F4
        pop edi                                         ; 06F9
L4_06FA:
        mov eax,[edi+0x59]                              ; 06FA
        or_ eax,eax                                     ; 06FD
        jz short L4_0734                                ; 06FF
        mov esi,D6_02D2                                 ; 0701
        cmp word [edi+0x8],byte -0x1                    ; 0706
        jnz short L4_0712                               ; 070B
        mov esi,D6_0270                                 ; 070D
L4_0712:
        movzx ecx,word [esi]                            ; 0712
        movzx edx,word [edi+0x6]                        ; 0715
        push edi                                        ; 0719
        mov_ edi,esi                                    ; 071A
        add esi,byte +0x2                               ; 071C
L4_071F:
        mov [esi],dx                                    ; 071F
        inc edx                                         ; 0722
        add esi,byte +0x6                               ; 0723
        loop L4_071F                                    ; 0726
        mov eax,[esp]                                   ; 0728
        mov eax,[eax+0x59]                              ; 072B
        call L4_01D3                                    ; 072E
        pop edi                                         ; 0733
L4_0734:
        mov eax,[edi+0x2d]                              ; 0734
        or_ eax,eax                                     ; 0737
        jz short L4_0741                                ; 0739
        VxDCall VPICD_Force_Default_Behavior            ; 073B
L4_0741:
        mov eax,[edi+0x31]                              ; 0741
        or_ eax,eax                                     ; 0744
        jz short L4_074E                                ; 0746
        VxDCall VPICD_Force_Default_Behavior            ; 0748
L4_074E:
        push byte +0x0                                  ; 074E
        push edi                                        ; 0750
        VxDCall _HeapFree                               ; 0751
        add esp,byte +0x8                               ; 0757
L4_075A:
        mov esi,[dword ADI_List]                        ; 075A
        mov eax,[ebp-0x4]                               ; 0760
        push eax                                        ; 0763
        VxDCall List_Remove                             ; 0764
        pop eax                                         ; 076A
        VxDCall List_Deallocate                         ; 076B
        popa                                            ; 0771
        add esp,byte +0x4                               ; 0772
        pop ebp                                         ; 0775
        ret                                             ; 0776
L4_0777:
        push ebp                                        ; 0777
        mov_ ebp,esp                                    ; 0778
        sub esp,byte +0x8                               ; 077A
        pusha                                           ; 077D
        mov dword [esp+0x1c],0x13                       ; 077E
        movzx edx,word [ebp+0xc]                        ; 0786
        push byte +0x2                                  ; 078A
        push edx                                        ; 078C
        call _AUDDRV_Get_pADI_From_XXX                  ; 078D
        add esp,byte +0x8                               ; 0792
        or_ edi,edi                                     ; 0795
        jnz near L4_08FB                                ; 0797
        call L4_0B6C                                    ; 079D
        jc near L4_0901                                 ; 07A2
        mov [ebp-0x4],ax                                ; 07A8
        mov [ebp-0x8],dx                                ; 07AC
        movzx edx,word [ebp+0xc]                        ; 07B0
        call L5_19FB                                    ; 07B4
        call L5_197F                                    ; 07B9
        call L5_1AD3                                    ; 07BE
        push edx                                        ; 07C3
        call Find_Config_Port                           ; 07C4
        add esp,byte +0x4                               ; 07C9
        mov al,[ebp+0x18]                               ; 07CC
        mov_ ah,al                                      ; 07CF
        test dword [ebp+0x24],0x2000                    ; 07D1
        jnz short L4_07DD                               ; 07D8
        mov ah,[ebp+0x2c]                               ; 07DA
L4_07DD:
        cmp edx,byte -0x1                               ; 07DD
        jz short L4_07EC                                ; 07E0
        mov ebx,[ebp+0x24]                              ; 07E2
        call L5_1BF2                                    ; 07E5
        jmp short L4_0803                               ; 07EA
L4_07EC:
        push dword [ebp+0x24]                           ; 07EC
        push eax                                        ; 07EF
        push dword [ebp+0xc]                            ; 07F0
        call L5_1AD4                                    ; 07F3
        add esp,byte +0xc                               ; 07F8
        or_ eax,eax                                     ; 07FB
        jz near L4_08FB                                 ; 07FD
L4_0803:
        movzx edx,word [ebp+0xc]                        ; 0803
        movsx ecx,word [ebp+0x28]                       ; 0807
        cmp ecx,byte -0x1                               ; 080B
        jz short L4_081A                                ; 080E
        call MPU_Reset                                  ; 0810
        call L1_09D0                                    ; 0815
L4_081A:
        push eax                                        ; 081A
        push dword D6_045A                              ; 081B
        push dword [ebp+0x8]                            ; 0820
        call L5_02B0                                    ; 0823
        add esp,byte +0x8                               ; 0828
        or_ eax,eax                                     ; 082B
        jnz short L4_0873                               ; 082D
        push dword D6_0462                              ; 082F
        push dword [ebp+0x8]                            ; 0834
        call L5_02B0                                    ; 0837
        add esp,byte +0x8                               ; 083C
        or_ eax,eax                                     ; 083F
        jnz short L4_0873                               ; 0841
        push dword D6_046A                              ; 0843
        push dword [ebp+0x8]                            ; 0848
        call L5_02B0                                    ; 084B
        add esp,byte +0x8                               ; 0850
        or_ eax,eax                                     ; 0853
        jnz short L4_0873                               ; 0855
        push dword D6_0472                              ; 0857
        push dword [ebp+0x8]                            ; 085C
        call L5_02B0                                    ; 085F
        add esp,byte +0x8                               ; 0864
        or_ eax,eax                                     ; 0867
        jnz short L4_0873                               ; 0869
        mov ebx,[ebp+0x24]                              ; 086B
        call L5_1EDB                                    ; 086E
L4_0873:
        pop eax                                         ; 0873
        call HwVol_Int_Disable                          ; 0874
        test dword [ebp+0x24],0x2                       ; 0879
        jnz short L4_088F                               ; 0880
        cmp word [ebp+0x14],byte -0x1                   ; 0882
        jnz short L4_088F                               ; 0887
        mov word [ebp+0x10],0xffff                      ; 0889
L4_088F:
        movsx edx,word [ebp+0x28]                       ; 088F
        cmp edx,byte -0x1                               ; 0893
        jz short L4_08AE                                ; 0896
        call L4_0BE9                                    ; 0898
        jc short L4_08FB                                ; 089D
        push dword [ebp+0x24]                           ; 089F
        push edx                                        ; 08A2
        push dword [ebp+0xc]                            ; 08A3
        call L5_1D39                                    ; 08A6
        add esp,byte +0xc                               ; 08AB
L4_08AE:
        test dword [ebp+0x24],0x4000000                 ; 08AE
        jz short L4_08C0                                ; 08B5
        movzx edx,word [ebp+0xc]                        ; 08B7
        call L5_1CE7                                    ; 08BB
L4_08C0:
        push dword [ebp+0x30]                           ; 08C0
        push dword [ebp+0x2c]                           ; 08C3
        push dword [ebp+0x28]                           ; 08C6
        push dword [ebp+0x24]                           ; 08C9
        push dword [ebp+0x20]                           ; 08CC
        push dword [ebp+0x1c]                           ; 08CF
        push dword [ebp+0x18]                           ; 08D2
        push dword [ebp-0x8]                            ; 08D5
        push dword [ebp+0x14]                           ; 08D8
        push dword [ebp+0x10]                           ; 08DB
        push dword [ebp-0x4]                            ; 08DE
        push dword [ebp+0xc]                            ; 08E1
        push dword [ebp+0x8]                            ; 08E4
        call ADI_Create                                 ; 08E7
        add esp,byte +0x34                              ; 08EC
        or_ eax,eax                                     ; 08EF
        jz short L4_08FB                                ; 08F1
        mov dword [esp+0x1c],0x0                        ; 08F3
L4_08FB:
        popa                                            ; 08FB
        add esp,byte +0x8                               ; 08FC
        pop ebp                                         ; 08FF
        ret                                             ; 0900
L4_0901:
        mov dword [esp+0x1c],0x24                       ; 0901
        jmp short L4_08FB                               ; 0909
L4_090B:
        push ebp                                        ; 090B
        mov_ ebp,esp                                    ; 090C
        push edi                                        ; 090E
        push ebx                                        ; 090F
        pushf                                           ; 0910
        xor_ edi,edi                                    ; 0911
        push dword [ebp+0x8]                            ; 0913
        call L4_0000                                    ; 0916
        add esp,byte +0x4                               ; 091B
        or_ eax,eax                                     ; 091E
        jz short L4_0966                                ; 0920
        push byte +0x0                                  ; 0922
        push dword [ebp+0x8]                            ; 0924
        call _AUDDRV_Get_pADI_From_XXX                  ; 0927
        add esp,byte +0x8                               ; 092C
        or_ edi,edi                                     ; 092F
        jz short L4_0966                                ; 0931
        mov ebx,[edi+0x35]                              ; 0933
        or_ ebx,ebx                                     ; 0936
        jz short L4_0944                                ; 0938
        mov eax,0x1                                     ; 093A
        call Release_Resources                          ; 093F
L4_0944:
        mov ebx,[edi+0x45]                              ; 0944
        or_ ebx,ebx                                     ; 0947
        jz short L4_0955                                ; 0949
        mov eax,0x4                                     ; 094B
        call Release_Resources                          ; 0950
L4_0955:
        mov ebx,[edi+0x3d]                              ; 0955
        or_ ebx,ebx                                     ; 0958
        jz short L4_0966                                ; 095A
        mov eax,0x2                                     ; 095C
        call Release_Resources                          ; 0961
L4_0966:
        push byte +0x0                                  ; 0966
        push dword [ebp+0x8]                            ; 0968
        call _AUDDRV_Get_pADI_From_XXX                  ; 096B
        add esp,byte +0x8                               ; 0970
        or_ edi,edi                                     ; 0973
        jz short L4_0991                                ; 0975
        mov eax,[edi+0x7a]                              ; 0977
        or_ eax,eax                                     ; 097A
        jz short L4_0984                                ; 097C
        VxDCall VDMAD_Phys_Mask_Channel                 ; 097E
L4_0984:
        mov eax,[edi+0x4d]                              ; 0984
        or_ eax,eax                                     ; 0987
        jz short L4_0991                                ; 0989
        VxDCall VDMAD_Phys_Mask_Channel                 ; 098B
L4_0991:
        mov ebx,[ebp+0x8]                               ; 0991
        mov esi,[dword ADI_List]                        ; 0994
        or_ esi,esi                                     ; 099A
        jz short L4_09DE                                ; 099C
        cli                                             ; 099E
        VxDCall List_Get_First                          ; 099F
        jz short L4_09DE                                ; 09A5
L4_09A7:
        mov edi,[eax]                                   ; 09A7
        cmp [edi+0x55],ebx                              ; 09A9
        jz short L4_09B8                                ; 09AC
        VxDCall List_Get_Next                           ; 09AE
        jz short L4_09DE                                ; 09B4
        jmp short L4_09A7                               ; 09B6
L4_09B8:
        popf                                            ; 09B8
        pushf                                           ; 09B9
        VxDCall Get_Sys_VM_Handle                       ; 09BA
        push ebx                                        ; 09C0
L4_09C1:
%if ESSREG_EXT
        call ESSREG_Node_Remove                         ; essreg: its virtual FM chip
%else
        call L4_00CB                                    ; 09C1
%endif
        VxDCall Get_Next_VM_Handle                      ; 09C6
        cmp ebx,[esp]                                   ; 09CC
        jnz short L4_09C1                               ; 09CF
        pop ebx                                         ; 09D1
        mov_ edi,eax                                    ; 09D2
        call L4_05EB                                    ; 09D4
        mov eax,0xffffffff                              ; 09D9
L4_09DE:
        popf                                            ; 09DE
        pop ebx                                         ; 09DF
        pop edi                                         ; 09E0
        pop ebp                                         ; 09E1
        ret                                             ; 09E2
L4_09E3:
        push ebp                                        ; 09E3
        mov_ ebp,esp                                    ; 09E4
        push edi                                        ; 09E6
        push byte +0x0                                  ; 09E7
        push dword [ebp+0x8]                            ; 09E9
        call _AUDDRV_Get_pADI_From_XXX                  ; 09EC
        add esp,byte +0x8                               ; 09F1
        or_ edi,edi                                     ; 09F4
        jz short L4_0A0F                                ; 09F6
        mov eax,[edi+0x8a]                              ; 09F8
        shl eax,1                                       ; 09FE
        cmp eax,[edi+0xd7]                              ; 0A00
        ja short L4_0A0F                                ; 0A06
        mov eax,0xffffffff                              ; 0A08
        jmp short L4_0A14                               ; 0A0D
L4_0A0F:
        mov eax,0x0                                     ; 0A0F
L4_0A14:
        pop edi                                         ; 0A14
        pop ebp                                         ; 0A15
        ret                                             ; 0A16
D4_0A17:
        db 0x55, 0x8b, 0xec, 0xff, 0x75, 0x18, 0xff, 0x75, 0x14, 0xff, 0x75, 0x10, 0xff, 0x75, 0x0c, 0xff ; 0A17
        db 0x75, 0x08                                   ; 0A27
        call L5_03E0                                    ; 0A29
        add esp,byte +0x14                              ; 0A2E
        leave                                           ; 0A31
        clc                                             ; 0A32
        ret                                             ; 0A33
L4_0A34:
        push ebp                                        ; 0A34
        mov_ ebp,esp                                    ; 0A35
        pusha                                           ; 0A37
        mov esi,[dword D1_02B1]                         ; 0A38
        or_ esi,esi                                     ; 0A3E
        jz short L4_0A68                                ; 0A40
        VxDCall List_Allocate                           ; 0A42
        jc short L4_0A68                                ; 0A48
        VxDCall List_Attach_Tail                        ; 0A4A
        mov edx,[ebp+0x8]                               ; 0A50
        mov [eax],edx                                   ; 0A53
        mov dx,[ebp+0xc]                                ; 0A55
        mov [eax+0x4],dx                                ; 0A59
        mov dword [esp+0x1c],0x0                        ; 0A5D
L4_0A65:
        popa                                            ; 0A65
        pop ebp                                         ; 0A66
        ret                                             ; 0A67
L4_0A68:
        mov dword [esp+0x1c],0x13                       ; 0A68
        jmp short L4_0A65                               ; 0A70
L4_0A72:
        push ebp                                        ; 0A72
        mov_ ebp,esp                                    ; 0A73
        push esi                                        ; 0A75
        push ebx                                        ; 0A76
        pushf                                           ; 0A77
        mov ebx,[ebp+0x8]                               ; 0A78
        mov esi,[dword D1_02B1]                         ; 0A7B
        or_ esi,esi                                     ; 0A81
        jz short L4_0AAC                                ; 0A83
        cli                                             ; 0A85
        VxDCall List_Get_First                          ; 0A86
        jz short L4_0AAC                                ; 0A8C
L4_0A8E:
        cmp [eax],ebx                                   ; 0A8E
        jz short L4_0A9C                                ; 0A90
        VxDCall List_Get_Next                           ; 0A92
        jz short L4_0AAC                                ; 0A98
        jmp short L4_0A8E                               ; 0A9A
L4_0A9C:
        popf                                            ; 0A9C
        pushf                                           ; 0A9D
        push eax                                        ; 0A9E
        VxDCall List_Remove                             ; 0A9F
        pop eax                                         ; 0AA5
        VxDCall List_Deallocate                         ; 0AA6
L4_0AAC:
        popf                                            ; 0AAC
        pop ebx                                         ; 0AAD
        pop esi                                         ; 0AAE
        pop ebp                                         ; 0AAF
        ret                                             ; 0AB0
D4_0AB1:
        db 0x55, 0x8b, 0xec, 0xff, 0x75, 0x18, 0xff, 0x75, 0x14, 0xff, 0x75, 0x10, 0xff, 0x75, 0x0c, 0xff ; 0AB1
        db 0x75, 0x08                                   ; 0AC1
        call L5_0AE0                                    ; 0AC3
        add esp,byte +0x14                              ; 0AC8
        leave                                           ; 0ACB
        clc                                             ; 0ACC
        ret                                             ; 0ACD
; PnP_New_DevNode: register device driver / enumerator
AUDDRV_PnP_New_DevNode:
        push ebp                                        ; 0ACE
        mov_ ebp,esp                                    ; 0ACF
        sub esp,byte +0x4                               ; 0AD1
        pusha                                           ; 0AD4
        push dword D6_0452                              ; 0AD5
        push ebx                                        ; 0ADA
        call L5_02B0                                    ; 0ADB
        add esp,byte +0x8                               ; 0AE0
        or_ eax,eax                                     ; 0AE3
        jnz short L4_0AF7                               ; 0AE5
        push dword D6_0449                              ; 0AE7
        push ebx                                        ; 0AEC
        call L5_02B0                                    ; 0AED
        add esp,byte +0x8                               ; 0AF2
        or_ eax,eax                                     ; 0AF5
L4_0AF7:
        popa                                            ; 0AF7
        jz short L4_0B0E                                ; 0AF8
        mov_ eax,ebx                                    ; 0AFA
        mov ebx,D4_0AB1                                 ; 0AFC
        VxDCall MMDEVLDR_Register_Device_Driver         ; 0B01
        mov eax,0x0                                     ; 0B07
        jmp short L4_0B64                               ; 0B0C
L4_0B0E:
        mov_ eax,esp                                    ; 0B0E
        push byte +0x0                                  ; 0B10
        push ebx                                        ; 0B12
        push eax                                        ; 0B13
        VxDCall CONFIGMG_Get_Parent                     ; 0B14
        add esp,byte +0xc                               ; 0B1A
        cmp eax,byte +0xd                               ; 0B1D
        jz short L4_0B52                                ; 0B20
        cmp eax,byte +0x0                               ; 0B22
        jz short L4_0B29                                ; 0B25
        jmp short L4_0B64                               ; 0B27
L4_0B29:
        push edi                                        ; 0B29
        mov eax,[esp+0x4]                               ; 0B2A
        push byte +0x0                                  ; 0B2E
        push eax                                        ; 0B30
        call _AUDDRV_Get_pADI_From_XXX                  ; 0B31
        add esp,byte +0x8                               ; 0B36
        or_ edi,edi                                     ; 0B39
        pop edi                                         ; 0B3B
        jz short L4_0B52                                ; 0B3C
        push byte +0x3                                  ; 0B3E
        push eax                                        ; 0B40
        push dword _AUDDRV_ND_PnP_ConfigHandler         ; 0B41
        push ebx                                        ; 0B46
        VxDCall CONFIGMG_Register_Device_Driver         ; 0B47
        add esp,byte +0x10                              ; 0B4D
        jmp short L4_0B64                               ; 0B50
L4_0B52:
        mov_ eax,ebx                                    ; 0B52
        mov ebx,D4_0A17                                 ; 0B54
        VxDCall MMDEVLDR_Register_Device_Driver         ; 0B59
        mov eax,0x0                                     ; 0B5F
L4_0B64:
        add esp,byte +0x4                               ; 0B64
        pop ebp                                         ; 0B67
        stc                                             ; 0B68
        ret                                             ; 0B69
        db 0xcc, 0xcc                                   ; 0B6A
L4_0B6C:
        push eax                                        ; 0B6C
        push edx                                        ; 0B6D
        add edx,byte +0x6                               ; 0B6E
        mov al,0x1                                      ; 0B71
        out dx,al                                       ; 0B73
        in al,dx                                        ; 0B74
        in al,dx                                        ; 0B75
        in al,dx                                        ; 0B76
        xor_ al,al                                      ; 0B77
        out dx,al                                       ; 0B79
        sub edx,byte +0x6                               ; 0B7A
        call L1_0960                                    ; 0B7D
        jc short L4_0BD6                                ; 0B82
        cmp al,0xaa                                     ; 0B84
        jnz short L4_0BD6                               ; 0B86
        mov al,0xe1                                     ; 0B88
        call L1_097C                                    ; 0B8A
        jc short L4_0BD6                                ; 0B8F
        call L1_0960                                    ; 0B91
        jc short L4_0BD6                                ; 0B96
        mov_ ah,al                                      ; 0B98
        call L1_0960                                    ; 0B9A
        jc short L4_0BD6                                ; 0B9F
        movzx eax,ax                                    ; 0BA1
        mov [esp+0x4],eax                               ; 0BA4
        mov al,0xe7                                     ; 0BA8
        call L1_097C                                    ; 0BAA
        jc short L4_0BD6                                ; 0BAF
        call L1_0960                                    ; 0BB1
        jc short L4_0BD6                                ; 0BB6
        mov_ ah,al                                      ; 0BB8
        call L1_0960                                    ; 0BBA
        jc short L4_0BD6                                ; 0BBF
        cmp ah,0x68                                     ; 0BC1
        jnz short L4_0BD6                               ; 0BC4
        mov_ ah,al                                      ; 0BC6
        and ah,0xf                                      ; 0BC8
        cmp ah,0x8                                      ; 0BCB
        jc short L4_0BD6                                ; 0BCE
        and al,0xf0                                     ; 0BD0
        cmp al,0x80                                     ; 0BD2
        jz short L4_0BDF                                ; 0BD4
L4_0BD6:
        xor_ eax,eax                                    ; 0BD6
        mov [esp+0x4],eax                               ; 0BD8
        stc                                             ; 0BDC
        jmp short L4_0BE6                               ; 0BDD
L4_0BDF:
        movzx eax,ah                                    ; 0BDF
        mov [esp],eax                                   ; 0BE2
        clc                                             ; 0BE5
L4_0BE6:
        pop edx                                         ; 0BE6
        pop eax                                         ; 0BE7
        ret                                             ; 0BE8
L4_0BE9:
        enter 0x8,0x0                                   ; 0BE9
        push eax                                        ; 0BED
        push ecx                                        ; 0BEE
        push edx                                        ; 0BEF
        mov dword [ebp-0x8],0x0                         ; 0BF0
L4_0BF7:
        mov dword [ebp-0x4],0x0                         ; 0BF7
        mov ecx,0x40                                    ; 0BFE
L4_0C03:
        inc edx                                         ; 0C03
        in al,dx                                        ; 0C04
        dec edx                                         ; 0C05
        test al,0x80                                    ; 0C06
        jnz short L4_0C0D                               ; 0C08
        in al,dx                                        ; 0C0A
        loop L4_0C03                                    ; 0C0B
L4_0C0D:
        mov ecx,0x1000                                  ; 0C0D
L4_0C12:
        inc edx                                         ; 0C12
        in al,dx                                        ; 0C13
        dec edx                                         ; 0C14
        test al,0x40                                    ; 0C15
        jz short L4_0C2F                                ; 0C17
        loop L4_0C12                                    ; 0C19
        cmp dword [ebp-0x4],byte +0x0                   ; 0C1B
        jnz short L4_0C59                               ; 0C1F
        mov dword [ebp-0x4],0xffffffff                  ; 0C21
        inc edx                                         ; 0C28
        mov al,0xff                                     ; 0C29
        out dx,al                                       ; 0C2B
        dec edx                                         ; 0C2C
        jmp short L4_0C0D                               ; 0C2D
L4_0C2F:
        mov al,0xff                                     ; 0C2F
        inc edx                                         ; 0C31
        out dx,al                                       ; 0C32
        dec edx                                         ; 0C33
        mov ecx,0x1000                                  ; 0C34
L4_0C39:
        inc edx                                         ; 0C39
        in al,dx                                        ; 0C3A
        dec edx                                         ; 0C3B
        test al,0x80                                    ; 0C3C
        jz short L4_0C51                                ; 0C3E
        loop L4_0C39                                    ; 0C40
        cmp dword [ebp-0x8],byte +0x0                   ; 0C42
        jnz short L4_0C59                               ; 0C46
        mov dword [ebp-0x8],0xffffffff                  ; 0C48
        jmp short L4_0BF7                               ; 0C4F
L4_0C51:
        in al,dx                                        ; 0C51
        cmp al,0xfe                                     ; 0C52
        jnz short L4_0C59                               ; 0C54
        clc                                             ; 0C56
        jmp short L4_0C5A                               ; 0C57
L4_0C59:
        stc                                             ; 0C59
L4_0C5A:
        pop edx                                         ; 0C5A
        pop ecx                                         ; 0C5B
        pop eax                                         ; 0C5C
        leave                                           ; 0C5D
        ret                                             ; 0C5E
        db 0xcc                                         ; 0C5F
; config handler of the VIRTUAL\ESS1869-DMAEmulation devnode
_AUDDRV_ND_PnP_ConfigHandler:
        push ebp                                        ; 0C60
        mov_ ebp,esp                                    ; 0C61
        push dword [ebp+0x18]                           ; 0C63
        push dword [ebp+0x14]                           ; 0C66
        push dword [ebp+0x10]                           ; 0C69
        push dword [ebp+0xc]                            ; 0C6C
        push dword [ebp+0x8]                            ; 0C6F
        call L5_0970                                    ; 0C72
        add esp,byte +0x14                              ; 0C77
        pop ebp                                         ; 0C7A
        clc                                             ; 0C7B
        ret                                             ; 0C7C
_AUDDRV_ND_Get_pADI_From_Child:
        push ebp                                        ; 0C7D
        mov_ ebp,esp                                    ; 0C7E
        sub esp,byte +0x4                               ; 0C80
        mov_ eax,esp                                    ; 0C83
        push byte +0x0                                  ; 0C85
        push dword [ebp+0x8]                            ; 0C87
        push eax                                        ; 0C8A
        VxDCall CONFIGMG_Get_Parent                     ; 0C8B
        add esp,byte +0xc                               ; 0C91
        cmp eax,byte +0x0                               ; 0C94
        jnz short L4_0CAD                               ; 0C97
        mov eax,[esp]                                   ; 0C99
        push edi                                        ; 0C9C
        push byte +0x0                                  ; 0C9D
        push eax                                        ; 0C9F
        call _AUDDRV_Get_pADI_From_XXX                  ; 0CA0
        add esp,byte +0x8                               ; 0CA5
        mov_ eax,edi                                    ; 0CA8
        pop edi                                         ; 0CAA
        jmp short L4_0CAF                               ; 0CAB
L4_0CAD:
        xor_ eax,eax                                    ; 0CAD
L4_0CAF:
        add esp,byte +0x4                               ; 0CAF
        leave                                           ; 0CB2
        ret                                             ; 0CB3
_AUDDRV_ND_Set_Config:
        push ebp                                        ; 0CB4
        mov_ ebp,esp                                    ; 0CB5
        push edi                                        ; 0CB7
        push esi                                        ; 0CB8
        push dword [ebp+0x8]                            ; 0CB9
        call _AUDDRV_ND_Get_pADI_From_Child             ; 0CBC
        add esp,byte +0x4                               ; 0CC1
        or_ eax,eax                                     ; 0CC4
        jz short L4_0D02                                ; 0CC6
        mov_ edi,eax                                    ; 0CC8
        mov esi,[ebp+0xc]                               ; 0CCA
        mov ax,[edi+0x6]                                ; 0CCD
        mov [esi],ax                                    ; 0CD1
        mov esi,[ebp+0x10]                              ; 0CD4
        movzx ax,[edi+0xf]                              ; 0CD7
        mov [esi],ax                                    ; 0CDC
        mov esi,[ebp+0x14]                              ; 0CDF
        movsx eax,word [esi]                            ; 0CE2
        cmp eax,byte -0x1                               ; 0CE5
        jz short L4_0D02                                ; 0CE8
        mov [edi+0x10],al                               ; 0CEA
        mov esi,L1_0518                                 ; 0CED
        VxDCall VDMAD_Virtualize_Channel                ; 0CF2
        mov [edi+0x4d],eax                              ; 0CF8
        mov eax,0x0                                     ; 0CFB
        jnc short L4_0D07                               ; 0D00
L4_0D02:
        mov eax,0x13                                    ; 0D02
L4_0D07:
        pop esi                                         ; 0D07
        pop edi                                         ; 0D08
        pop ebp                                         ; 0D09
        ret                                             ; 0D0A
_AUDDRV_ND_Remove_Config:
        push ebp                                        ; 0D0B
        mov_ ebp,esp                                    ; 0D0C
        push edi                                        ; 0D0E
        push dword [ebp+0x8]                            ; 0D0F
        call _AUDDRV_ND_Get_pADI_From_Child             ; 0D12
        add esp,byte +0x4                               ; 0D17
        or_ eax,eax                                     ; 0D1A
        jz short L4_0D3D                                ; 0D1C
        mov_ edi,eax                                    ; 0D1E
        mov eax,[edi+0x4d]                              ; 0D20
        or_ eax,eax                                     ; 0D23
        jz short L4_0D36                                ; 0D25
        VxDCall VDMAD_Unvirtualize_Channel              ; 0D27
        xor_ eax,eax                                    ; 0D2D
        mov [edi+0x4d],eax                              ; 0D2F
        dec eax                                         ; 0D32
        mov [edi+0x10],al                               ; 0D33
L4_0D36:
        mov eax,0x0                                     ; 0D36
        jmp short L4_0D42                               ; 0D3B
L4_0D3D:
        mov eax,0x13                                    ; 0D3D
L4_0D42:
        pop edi                                         ; 0D42
        pop ebp                                         ; 0D43
        ret                                             ; 0D44
_AUDDRV_ND_IsOwned:
        push ebp                                        ; 0D45
        mov_ ebp,esp                                    ; 0D46
        push dword [ebp+0x8]                            ; 0D48
        call _AUDDRV_ND_Get_pADI_From_Child             ; 0D4B
        add esp,byte +0x4                               ; 0D50
        or_ eax,eax                                     ; 0D53
        jz short L4_0D69                                ; 0D55
        cmp dword [eax+0x35],byte +0x0                  ; 0D57
        jz short L4_0D64                                ; 0D5B
        mov eax,0xffffffff                              ; 0D5D
        jmp short L4_0D69                               ; 0D62
L4_0D64:
        mov eax,0x0                                     ; 0D64
L4_0D69:
        pop ebp                                         ; 0D69
        ret                                             ; 0D6A
        db 0xcc                                         ; 0D6B
