; RARE is object 3 of ES1869.VXD (code and data, flags 2005h).
; Generated by tools/vxd2asm.py, then maintained by hand.
; Trailing comments give the original object offset.

section RARE progbits alloc exec nowrite align=1

; Sys_Dynamic_Device_Exit
AUDDRV_Dynamic_Exit:
        mov eax,0x15000e                                ; 0000
        mov esi,L1_04B8                                 ; 0005
        VxDCall VMM_Service_011C                        ; 000A
        xor_ esi,esi                                    ; 0010
        xchg esi,[dword D1_02B1]                        ; 0012
        or_ esi,esi                                     ; 0018
        jz short L3_005C                                ; 001A
        VxDCall List_Destroy                            ; 001C
        xor_ esi,esi                                    ; 0022
        xchg esi,[dword ADI_List]                       ; 0024
        or_ esi,esi                                     ; 002A
        jz short L3_005C                                ; 002C
        VxDCall List_Destroy                            ; 002E
        VxDCall Get_Sys_VM_Handle                       ; 0034
        mov edi,[dword AUDDRV_Globals]                  ; 003A
        push ebx                                        ; 0040
L3_0041:
        xor_ esi,esi                                    ; 0041
        xchg esi,[edi+ebx]                              ; 0043
        or_ esi,esi                                     ; 0046
        jz short L3_0050                                ; 0048
        VxDCall List_Destroy                            ; 004A
L3_0050:
        VxDCall Get_Next_VM_Handle                      ; 0050
        cmp ebx,[esp]                                   ; 0056
        jnz short L3_0041                               ; 0059
        pop ebx                                         ; 005B
L3_005C:
        clc                                             ; 005C
        ret                                             ; 005D
L3_005E:
        push ebp                                        ; 005E
        mov_ ebp,esp                                    ; 005F
        push eax                                        ; 0061
        push ebx                                        ; 0062
        push edi                                        ; 0063
        push esi                                        ; 0064
        push byte +0x0                                  ; 0065
        push dword [ebp+0x8]                            ; 0067
        call _AUDDRV_Get_pADI_From_XXX                  ; 006A
        add esp,byte +0x8                               ; 006F
        or_ edi,edi                                     ; 0072
        jz near L3_012A                                 ; 0074
        mov ebx,[edi+0x35]                              ; 007A
        or_ ebx,ebx                                     ; 007D
        jz near L3_0120                                 ; 007F
        call L1_0479                                    ; 0085
        jc near L3_012A                                 ; 008A
        call L5_2032                                    ; 0090
        push ecx                                        ; 0095
        push edx                                        ; 0096
        push edi                                        ; 0097
        mov eax,[edi+0x4d]                              ; 0098
        or_ eax,eax                                     ; 009B
        jz short L3_00C1                                ; 009D
        mov_ edi,esi                                    ; 009F
        VxDCall VDMAD_Get_Virt_State                    ; 00A1
        mov [edi+0x20],dx                               ; 00A7
        mov [edi+0x18],ecx                              ; 00AB
        mov [edi+0x1c],esi                              ; 00AE
        mov_ esi,edi                                    ; 00B1
        test word [esi+0x20],0x1                        ; 00B3
        jnz short L3_00C1                               ; 00B9
        VxDCall VDMAD_Mask_Channel                      ; 00BB
L3_00C1:
        pop edi                                         ; 00C1
        VxDCall Test_Sys_VM_Handle                      ; 00C2
        jz short L3_00D3                                ; 00C8
        movzx edx,word [edi+0x6]                        ; 00CA
        call DSP_Reset                                  ; 00CE
L3_00D3:
        push edi                                        ; 00D3
        mov eax,[edi+0x7a]                              ; 00D4
        or_ eax,eax                                     ; 00D7
        jz short L3_00FD                                ; 00D9
        mov_ edi,esi                                    ; 00DB
        VxDCall VDMAD_Get_Virt_State                    ; 00DD
        mov [edi+0x2c],dx                               ; 00E3
        mov [edi+0x24],ecx                              ; 00E7
        mov [edi+0x28],esi                              ; 00EA
        mov_ esi,edi                                    ; 00ED
        test word [esi+0x2c],0x1                        ; 00EF
        jnz short L3_00FD                               ; 00F5
        VxDCall VDMAD_Mask_Channel                      ; 00F7
L3_00FD:
        pop edi                                         ; 00FD
        VxDCall Test_Sys_VM_Handle                      ; 00FE
        jnz short L3_010F                               ; 0104
        pop edx                                         ; 0106
        pop ecx                                         ; 0107
        call L5_1FC8                                    ; 0108
        jmp short L3_012A                               ; 010D
L3_010F:
        movzx edx,word [edi+0x6]                        ; 010F
        call L5_197F                                    ; 0113
        pop edx                                         ; 0118
        pop ecx                                         ; 0119
        or word [edi+0x4],0x100                         ; 011A
L3_0120:
        call L5_20AE                                    ; 0120
        call Local_Powerdown                            ; 0125
L3_012A:
        pop esi                                         ; 012A
        pop edi                                         ; 012B
        pop ebx                                         ; 012C
        pop eax                                         ; 012D
        pop ebp                                         ; 012E
        ret                                             ; 012F
L3_0130:
        push ebp                                        ; 0130
        mov_ ebp,esp                                    ; 0131
        push eax                                        ; 0133
        push ebx                                        ; 0134
        push edi                                        ; 0135
        push esi                                        ; 0136
        push byte +0x0                                  ; 0137
        push dword [ebp+0x8]                            ; 0139
        call _AUDDRV_Get_pADI_From_XXX                  ; 013C
        add esp,byte +0x8                               ; 0141
        or_ edi,edi                                     ; 0144
        jz near L3_0226                                 ; 0146
        mov ebx,[edi+0x35]                              ; 014C
        or_ ebx,ebx                                     ; 014F
        jz short L3_015B                                ; 0151
        VxDCall Test_Sys_VM_Handle                      ; 0153
        jz short L3_0191                                ; 0159
L3_015B:
        call Wake_From_Local_Powerdown                  ; 015B
        push edx                                        ; 0160
        movzx edx,word [edi+0x6]                        ; 0161
        call DSP_Reset                                  ; 0165
        pop edx                                         ; 016A
        jc short L3_0172                                ; 016B
        call L5_1C37                                    ; 016D
L3_0172:
        push edx                                        ; 0172
        movzx edx,word [edi+0x6]                        ; 0173
        call L5_197F                                    ; 0177
        pop edx                                         ; 017C
        or_ ebx,ebx                                     ; 017D
        jz near L3_0226                                 ; 017F
        test word [edi+0x4],0x100                       ; 0185
        jz near L3_0226                                 ; 018B
L3_0191:
        call L1_0479                                    ; 0191
        jc near L3_0226                                 ; 0196
        call L5_2024                                    ; 019C
        push ecx                                        ; 01A1
        push edx                                        ; 01A2
        push edi                                        ; 01A3
        mov eax,[edi+0x4d]                              ; 01A4
        or_ eax,eax                                     ; 01A7
        jz short L3_01CA                                ; 01A9
        mov_ edi,esi                                    ; 01AB
        mov dx,[edi+0x20]                               ; 01AD
        mov ecx,[edi+0x18]                              ; 01B1
        mov esi,[edi+0x1c]                              ; 01B4
        VxDCall VDMAD_Set_Virt_State                    ; 01B7
        mov_ esi,edi                                    ; 01BD
        test dl,0x1                                     ; 01BF
        jnz short L3_01CA                               ; 01C2
        VxDCall VDMAD_UnMask_Channel                    ; 01C4
L3_01CA:
        pop edi                                         ; 01CA
        VxDCall Test_Sys_VM_Handle                      ; 01CB
        jz short L3_01DC                                ; 01D1
        movzx edx,word [edi+0x6]                        ; 01D3
        call DSP_Reset                                  ; 01D7
L3_01DC:
        push edi                                        ; 01DC
        mov eax,[edi+0x7a]                              ; 01DD
        or_ eax,eax                                     ; 01E0
        jz short L3_0203                                ; 01E2
        mov_ edi,esi                                    ; 01E4
        mov dx,[edi+0x2c]                               ; 01E6
        mov ecx,[edi+0x24]                              ; 01EA
        mov esi,[edi+0x28]                              ; 01ED
        VxDCall VDMAD_Set_Virt_State                    ; 01F0
        mov_ esi,edi                                    ; 01F6
        test dl,0x1                                     ; 01F8
        jnz short L3_0203                               ; 01FB
        VxDCall VDMAD_UnMask_Channel                    ; 01FD
L3_0203:
        pop edi                                         ; 0203
        VxDCall Test_Sys_VM_Handle                      ; 0204
        jnz short L3_0215                               ; 020A
        pop edx                                         ; 020C
        pop ecx                                         ; 020D
        call L5_2000                                    ; 020E
        jmp short L3_0226                               ; 0213
L3_0215:
        movzx edx,word [edi+0x6]                        ; 0215
        call L5_197F                                    ; 0219
        pop edx                                         ; 021E
        pop ecx                                         ; 021F
        and word [edi+0x4],0xfeff                       ; 0220
L3_0226:
        pop esi                                         ; 0226
        pop edi                                         ; 0227
        pop ebx                                         ; 0228
        pop eax                                         ; 0229
        pop ebp                                         ; 022A
        ret                                             ; 022B
